[package]
name = "cgisf"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = { version = "0.8.5", features = ["std"] }
clap = { version = "3.2.1", features = ["derive"] }
